export const pakistanCities = [
  "Karachi",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Sialkot",
  "Gujranwala",
  "Hyderabad",
  "Bahawalpur",
  "Sargodha",
  "Sukkur",
  "Larkana",
  "Sheikhupura",
  "Jhang",
  "Rahim Yar Khan",
  "Gujrat",
  "Mardan",
  "Kasur",
  "Mingora",
  "Dera Ghazi Khan",
  "Nawabshah",
  "Sahiwal",
  "Mirpur Khas",
  "Okara",
  "Mandi Bahauddin",
  "Jacobabad",
  "Jhelum",
  "Abbottabad",
  "Muzaffarabad",
  "Kohat",
  "Bannu",
  "Chiniot",
  "Kamoke",
  "Hafizabad",
  "Sadiqabad",
  "Burewala",
  "Khanewal",
];
